name: Node CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
    - name: Use Node.js 18.x
      uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
      with:
        node-version: 22
    - name: npm install
      run: npm install
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
    - name: Run tests
      run: npm test
      env:
        CI: true
